### PR TITLE
Null guard proposals_controller to allow commentless votes

### PR DESCRIPTION
**Pull request by ThePletch**

### CODE REVIEW

**Comment by ThePletch** [comment]
I'll add a spec to this after work to avoid this happening again.

**Comment by kimardenmiller** [comment]
Thank you, Steve.


/k

**Comment by kimardenmiller** [comment]
@ThePletch, Just wanted to check back with you to see if you wanted to do any tests for this code before I emerged it, or if I should go ahead and merge. No problem either way, just let me know. :-)

**Comment by kimardenmiller** [comment]
Very nice. Thanks @ThePletch

**Pull request merged**
